-- @connection: churchcrm
--
-- Which database this migration belongs to. migrations/portal/ holds
-- migrations for BOTH the portal database and the ChurchCRM database
-- (member import staging and events live alongside person_per), so the
-- target cannot be inferred from the directory name.
-- Associate an event with a ministry.
--
-- Events could already carry a campus, a host campus and a custom location, but
-- nothing recorded which ministry an activity belongs to — so "Instruments
-- Training" and a church-wide holiday were indistinguishable, and the Events
-- list could not show or filter by ministry.
--
-- Ministries live in the portal database while events live alongside person_per,
-- so this is a plain nullable id rather than a foreign key. NULL means
-- church-wide, which is the correct default for Communion Sunday or a holiday.
--
-- Idempotent and safe to re-run. Uses MariaDB's IF NOT EXISTS rather than a
-- PREPARE/EXECUTE block: the block is correct when piped to the mysql client
-- but breaks any runner that splits the file on semicolons, which is how it
-- failed on first application to production.
ALTER TABLE `events_event` ADD COLUMN IF NOT EXISTS `ministry_id` INT NULL DEFAULT NULL AFTER `event_text`;
CREATE INDEX IF NOT EXISTS `idx_events_ministry` ON `events_event` (`ministry_id`);
